package dsa_assignment.UI;
import dsa_assignment.entity.Student;
import dsa_assignment.entity.Course;
import dsa_assignment.entity.Faculty;
import dsa_assignment.*;
import java.awt.Component;
import dsa_assignment.adt.Filter.*;
import dsa_assignment.adt.Indexing.HashMap;
import dsa_assignment.adt.Indexing.Map;
import dsa_assignment.helper.*;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.util.Calendar;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.*;

public class addStudent extends javax.swing.JFrame {
    private final int key = 101;
    FileHandling f = new FileHandling();
  //  private List <ComboItem> cItmp = new ArrayList<>(); 
    //temporary how combobox key and value
    public addStudent() {
       Student s = new Student();
        initComponents();
                  
       jComboBoxCourse.setPrototypeDisplayValue("XXXXXXXXXXXXXXXXXXXXXXXXXX");

        this.setLocationRelativeTo(null);
        this.setResizable(false);
        //generate month and year for session/
        String month = (Calendar.getInstance().get(Calendar.MONTH) + 1) +"";
        String newStudId = s.generateNewId();
        lblStudID.setText(newStudId);
        lblSession.setText(month+newStudId.substring(0,2));
        
        //disable text area horizontal scroll
        jTextAreaAddress.setLineWrap(true);  
        jTextAreaAddress.setWrapStyleWord(true);
        
        groupButton();
         
        addFacultyToDDL();//add faculty to jcombobox
        
        for(int i= 1; i<=8;i++)  //add tutorial group to jcombobox
            jComboBoxTutorialGroup.addItem(i+"");
    }
    
    public void addFacultyToDDL(){ 
        FileHandling f = new FileHandling();
        List <Faculty> fac = f.readFaculty("src/data/faculty.txt");
       jComboBoxFaculty.addItem(new ComboItem("0","--Select One--"));
       for(int i=0;i<fac.size();i++){
           Faculty ff = new Faculty();
           jComboBoxFaculty.addItem(new ComboItem(fac.get(i).getAbbreviation(),fac.get(i).getFacultyName()));
        }        

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupGender = new javax.swing.ButtonGroup();
        jFrameAddStudent = new javax.swing.JFrame();
        jTextFieldAddStudent = new javax.swing.JPanel();
        jLabelAddStudent = new javax.swing.JLabel();
        jLabelID = new javax.swing.JLabel();
        jLabelFName = new javax.swing.JLabel();
        jLabelLName = new javax.swing.JLabel();
        jLabelGender = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelPhoneNum = new javax.swing.JLabel();
        jLabelAddress = new javax.swing.JLabel();
        jLabelFaculty = new javax.swing.JLabel();
        jLabelPersonalInfo = new javax.swing.JLabel();
        jLabelCourse = new javax.swing.JLabel();
        jLabelTutorialGroup = new javax.swing.JLabel();
        jLabelSession = new javax.swing.JLabel();
        jLabelOtherInfo = new javax.swing.JLabel();
        jTextFieldFName = new javax.swing.JTextField();
        jTextFieldLName = new javax.swing.JTextField();
        jRadioButtonMale = new javax.swing.JRadioButton();
        jRadioButtonFemale = new javax.swing.JRadioButton();
        jTextFieldPhoneNum = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaAddress = new javax.swing.JTextArea();
        jComboBoxCourse = new javax.swing.JComboBox<>();
        lblStudID = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jButtonAdd = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jComboBoxTutorialGroup = new javax.swing.JComboBox<>();
        lblSession = new javax.swing.JLabel();
        jComboBoxFaculty = new javax.swing.JComboBox<>();

        javax.swing.GroupLayout jFrameAddStudentLayout = new javax.swing.GroupLayout(jFrameAddStudent.getContentPane());
        jFrameAddStudent.getContentPane().setLayout(jFrameAddStudentLayout);
        jFrameAddStudentLayout.setHorizontalGroup(
            jFrameAddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrameAddStudentLayout.setVerticalGroup(
            jFrameAddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelAddStudent.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelAddStudent.setText("Add Student");

        jLabelID.setText("ID:");

        jLabelFName.setText("First Name:");

        jLabelLName.setText("Last Name:");

        jLabelGender.setText("Gender:");

        jLabelEmail.setText("Email:");

        jLabelPhoneNum.setText("Phone No:");

        jLabelAddress.setText("Address:");

        jLabelFaculty.setText("Faculty:");

        jLabelPersonalInfo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelPersonalInfo.setText("Personal Information");
        jLabelPersonalInfo.setToolTipText("");

        jLabelCourse.setText("Course:");

        jLabelTutorialGroup.setText("Tutorial Group:");

        jLabelSession.setText("Session: ");

        jLabelOtherInfo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelOtherInfo.setText("Other Information");
        jLabelOtherInfo.setToolTipText("");

        jTextFieldFName.setToolTipText("First Name");
        jTextFieldFName.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jTextFieldFName.setVerifyInputWhenFocusTarget(false);
        jTextFieldFName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldFNameKeyPressed(evt);
            }
        });

        jTextFieldLName.setToolTipText("Last Name");
        jTextFieldLName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldLNameKeyPressed(evt);
            }
        });

        jRadioButtonMale.setSelected(true);
        jRadioButtonMale.setText("Male");
        jRadioButtonMale.setToolTipText("");

        jRadioButtonFemale.setText("Female");

        jTextFieldPhoneNum.setToolTipText("Phone Number");
        jTextFieldPhoneNum.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPhoneNumKeyPressed(evt);
            }
        });

        jTextAreaAddress.setColumns(20);
        jTextAreaAddress.setRows(5);
        jTextAreaAddress.setToolTipText("Address");
        jScrollPane2.setViewportView(jTextAreaAddress);

        jComboBoxCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select One--" }));
        jComboBoxCourse.setToolTipText("Course");
        jComboBoxCourse.setMaximumSize(new java.awt.Dimension(109, 22));

        lblStudID.setText("jLabel1");

        jTextFieldEmail.setToolTipText("Email");
        jTextFieldEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldEmailKeyPressed(evt);
            }
        });

        jButtonAdd.setText("Add");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jComboBoxTutorialGroup.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select One--" }));

        lblSession.setText("jLabel2");

        jComboBoxFaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFacultyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jTextFieldAddStudentLayout = new javax.swing.GroupLayout(jTextFieldAddStudent);
        jTextFieldAddStudent.setLayout(jTextFieldAddStudentLayout);
        jTextFieldAddStudentLayout.setHorizontalGroup(
            jTextFieldAddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTextFieldAddStudentLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jTextFieldAddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jTextFieldAddStudentLayout.createSequentialGroup()
                        .addGroup(jTextFieldAddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelOtherInfo)
                            .addComponent(jLabelID)
                            .addComponent(jLabelFName)
                            .addComponent(jLabelLName)
                            .addComponent(jLabelGender)
                            .addComponent(jLabelEmail)
                            .addComponent(jLabelPhoneNum)
                            .addComponent(jLabelAddress)
                            .addComponent(jLabelFaculty)
                            .addComponent(jLabelCourse)
                            .addComponent(jLabelTutorialGroup)
                            .addComponent(jLabelSession))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jTextFieldAddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxTutorialGroup, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldFName)
                            .addComponent(jTextFieldLName)
                            .addComponent(jTextFieldEmail)
                            .addComponent(jTextFieldPhoneNum)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)
                            .addGroup(jTextFieldAddStudentLayout.createSequentialGroup()
                                .addGroup(jTextFieldAddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jTextFieldAddStudentLayout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addGroup(jTextFieldAddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblStudID)
                                            .addGroup(jTextFieldAddStudentLayout.createSequentialGroup()
                                                .addComponent(jRadioButtonMale)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jRadioButtonFemale))))
                                    .addComponent(lblSession))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jComboBoxFaculty, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBoxCourse, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabelPersonalInfo))
                .addGap(40, 40, 40))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jTextFieldAddStudentLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jTextFieldAddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jTextFieldAddStudentLayout.createSequentialGroup()
                        .addComponent(jButtonAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCancel)
                        .addGap(156, 156, 156))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jTextFieldAddStudentLayout.createSequentialGroup()
                        .addComponent(jLabelAddStudent)
                        .addGap(145, 145, 145))))
        );
        jTextFieldAddStudentLayout.setVerticalGroup(
            jTextFieldAddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTextFieldAddStudentLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabelAddStudent, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelPersonalInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jTextFieldAddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jTextFieldAddStudentLayout.createSequentialGroup()
                        .addGroup(jTextFieldAddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelID)
                            .addComponent(lblStudID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jTextFieldAddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelFName)
                            .addComponent(jTextFieldFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelLName)
                        .addGap(12, 12, 12)
                        .addComponent(jLabelGender))
                    .addGroup(jTextFieldAddStudentLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jTextFieldLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jTextFieldAddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonMale)
                            .addComponent(jRadioButtonFemale))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jTextFieldAddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelEmail)
                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jTextFieldAddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelPhoneNum)
                    .addComponent(jTextFieldPhoneNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jTextFieldAddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelAddress)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabelOtherInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jTextFieldAddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFaculty)
                    .addComponent(jComboBoxFaculty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jTextFieldAddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCourse)
                    .addComponent(jComboBoxCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jTextFieldAddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTutorialGroup)
                    .addComponent(jComboBoxTutorialGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jTextFieldAddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSession)
                    .addComponent(lblSession))
                .addGap(30, 30, 30)
                .addGroup(jTextFieldAddStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAdd)
                    .addComponent(jButtonCancel))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        jTextFieldFName.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(150, Short.MAX_VALUE)
                .addComponent(jTextFieldAddStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jTextFieldAddStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:
       ComboItem selected_item = (ComboItem) jComboBoxFaculty.getSelectedItem();
        Map<Integer,Student>  hmap =new HashMap<>();
                  List <Integer>hashMap = new ArrayList<>();

        String studId = lblStudID.getText();
        String fName = jTextFieldFName.getText();
        String lName = jTextFieldLName.getText();
        char gender = jRadioButtonMale.isSelected()?'M':'F';  
        String email = jTextFieldEmail.getText();
        String phoneNumber = jTextFieldPhoneNum.getText();
        String address = jTextAreaAddress.getText();
        String faculty = selected_item.getId()+"";
        String course = jComboBoxCourse.getSelectedItem()+"";
        int tutorialGroup = Integer.parseInt(jComboBoxTutorialGroup.getSelectedItem()+"");
        String session = lblSession.getText();
        
        hmap.put(key,new Student(key,
                    studId,fName,lName,gender,email,phoneNumber,address,
                    new Faculty(faculty),new Course(course),
                    tutorialGroup,session
                 ));
        Student s = new Student(Math.abs(hmap.hashCode()),
                studId,fName,lName,gender,email,phoneNumber,address,
                new Faculty(faculty),new Course(course),
               tutorialGroup,session);     
         s.savetoFile();      
        showMessageDialog(null, "Student Added Successfully");
        this.setVisible(false);
         MainPage main = new MainPage();
        main.setVisible(true);
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
       this.setVisible(false);
       MainPage main = new MainPage();
       main.setVisible(true);
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jComboBoxFacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFacultyActionPerformed
        // TODO add your handling code here:

        jComboBoxCourse.removeAllItems();
        jComboBoxCourse.addItem(new ComboItem("0","--Select One--")+"");
        ComboItem selected_item = (ComboItem) jComboBoxFaculty.getSelectedItem();

        List c = f.readSelectedCourse("src/data/course.txt",selected_item.getId() );
        for(int i =0;i<c.size(); i++){
            jComboBoxCourse.addItem(c.get(i)+"");
        }
    }//GEN-LAST:event_jComboBoxFacultyActionPerformed

    private void jTextFieldFNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldFNameKeyPressed
        setTextFieldMax(jTextFieldFName,30);
    }//GEN-LAST:event_jTextFieldFNameKeyPressed

    private void jTextFieldLNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldLNameKeyPressed
        setTextFieldMax(jTextFieldLName,30);
    }//GEN-LAST:event_jTextFieldLNameKeyPressed

    private void jTextFieldEmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldEmailKeyPressed
        setTextFieldMax(jTextFieldEmail,50);

    }//GEN-LAST:event_jTextFieldEmailKeyPressed

    private void jTextFieldPhoneNumKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPhoneNumKeyPressed
        setTextFieldMax( jTextFieldPhoneNum,12);
        
    }//GEN-LAST:event_jTextFieldPhoneNumKeyPressed
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addStudent().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupGender;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JComboBox<String> jComboBoxCourse;
    private javax.swing.JComboBox<ComboItem> jComboBoxFaculty;
    private javax.swing.JComboBox<String> jComboBoxTutorialGroup;
    private javax.swing.JFrame jFrameAddStudent;
    private javax.swing.JLabel jLabelAddStudent;
    private javax.swing.JLabel jLabelAddress;
    private javax.swing.JLabel jLabelCourse;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelFName;
    private javax.swing.JLabel jLabelFaculty;
    private javax.swing.JLabel jLabelGender;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelLName;
    private javax.swing.JLabel jLabelOtherInfo;
    private javax.swing.JLabel jLabelPersonalInfo;
    private javax.swing.JLabel jLabelPhoneNum;
    private javax.swing.JLabel jLabelSession;
    private javax.swing.JLabel jLabelTutorialGroup;
    private javax.swing.JRadioButton jRadioButtonFemale;
    private javax.swing.JRadioButton jRadioButtonMale;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextAreaAddress;
    private javax.swing.JPanel jTextFieldAddStudent;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldFName;
    private javax.swing.JTextField jTextFieldLName;
    private javax.swing.JTextField jTextFieldPhoneNum;
    private javax.swing.JLabel lblSession;
    private javax.swing.JLabel lblStudID;
    // End of variables declaration//GEN-END:variables
        
    private void groupButton( ) {
        ButtonGroup bg1 = new ButtonGroup( );
        bg1.add(jRadioButtonMale);
        bg1.add(jRadioButtonFemale);
    }
    private void setTextFieldMax(JTextField j, int maxLength){
         if(j.getText().length()>maxLength)
        {
            j.setText(j.getText().substring(0, maxLength));
        }
    }

}







