/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dsa_assignment.UI;

import dsa_assignment.MainPage;
import dsa_assignment.helper.JavaxSwingHelper;
import dsa_assignment.adt.Filter.List;
import dsa_assignment.entity.Student;
import dsa_assignment.helper.FileHandling;
import java.io.PrintStream;
import javax.swing.*;
import dsa_assignment.helper.TextAreaOutputStream;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;


/**
 *
 * @author user
 */
public class Filter extends javax.swing.JFrame {

    JavaxSwingHelper j = new JavaxSwingHelper();

    public Filter() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        jTextAreaSearched.setEditable(false);
        // catch the enter key in the jTextFieldSearchStr and 
        //  perform an search click on the jButtonSearch
        j.enterKeyControl(jTextFieldSearchStr, jButtonSearch);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTItle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaSearched = new javax.swing.JTextArea();
        jButtonBack = new javax.swing.JButton();
        jTextFieldSearchStr = new javax.swing.JTextField();
        jButtonSearch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTItle.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelTItle.setText("Filter");

        jTextAreaSearched.setColumns(20);
        jTextAreaSearched.setFont(new java.awt.Font("MS Gothic", 0, 13)); // NOI18N
        jTextAreaSearched.setRows(5);
        jScrollPane1.setViewportView(jTextAreaSearched);

        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });

        jButtonSearch.setText("Search");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Search for: ID, First Name, Last Name");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(421, 421, 421)
                        .addComponent(jLabelTItle))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldSearchStr, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonSearch)))))
                .addContainerGap(314, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonBack)
                .addGap(426, 426, 426))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabelTItle)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldSearchStr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSearch))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jButtonBack)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        j.back(this);
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        if(jTextFieldSearchStr.getText().length() == 0){//ensure searchSrting has value
            //clear jTextAreaSearched
            jTextAreaSearched.selectAll();
            jTextAreaSearched.replaceSelection("");
        }else{
            jTextAreaSearched.selectAll();
            jTextAreaSearched.replaceSelection("");
            PrintStream out = new PrintStream( new TextAreaOutputStream( jTextAreaSearched ) );
            //output to JTextArea
            System.setOut( out );
            System.setErr( out );
            filter();
        }
    }//GEN-LAST:event_jButtonSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Filter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Filter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Filter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Filter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Filter().setVisible(true);
            }
        });
    }
    public void filter(){
        FileHandling f = new FileHandling();
        List <Student> stud =  f.fileToList();
        Student s =new Student();
        boolean found = false;
        int count =0 ;
        String searchStr = jTextFieldSearchStr.getText();
        searchStr = searchStr.toUpperCase();        

        String output ="";
        for(int i =0;i < stud.size();i++){
            boolean idCondition= stud.get(i).getId().toUpperCase().contains(searchStr);
            boolean fNameCondition= stud.get(i).getfName().toUpperCase().contains(searchStr);
            boolean lNameCondition=stud.get(i).getlName().toUpperCase().contains(searchStr);
            //Gender == firstname(Search)
            //if((stud.get(i).getGender()+"").equals("F") && stud.get(i).getfName().toUpperCase().contains(searchStr)){
            //if((stud.get(i).getGender()+"").equals("G") && stud.get(i).getfName().toUpperCase().contains(searchStr)){

                //Gender == lastname(Search)
            //if((stud.get(i).getGender()+"").equals("F") && stud.get(i).getlName().toUpperCase().contains(searchStr)){
            //if((stud.get(i).getGender()+"").equals("G") && stud.get(i).getlName().toUpperCase().contains(searchStr)){    

                //Gender == address(Search)
            //if((stud.get(i).getGender()+"").equals("F") && stud.get(i).getAddress().toUpperCase().contains(searchStr)){    
            //if((stud.get(i).getGender()+"").equals("G") && stud.get(i).getAddress().toUpperCase().contains(searchStr)){ 

                //Gender == faculty(Search)
            //if((stud.get(i).getGender()+"").equals("F") && stud.get(i).getFacultyAbbr().getAbbreviation().toUpperCase().contains(searchStr)){     
            //if((stud.get(i).getGender()+"").equals("G") && stud.get(i).getFacultyAbbr().getAbbreviation().toUpperCase().contains(searchStr)){ 

                //Facuty == course(Search)
            //if(stud.get(i).getFacultyAbbr().getAbbreviation().equals("FOCS") && stud.get(i).getCourseName().getCourseName().toUpperCase().contains(searchStr)){   
            //if(stud.get(i).getFacultyAbbr().getAbbreviation().equals("FAFB") && stud.get(i).getCourseName().getCourseName().toUpperCase().contains(searchStr)){  
            //if(stud.get(i).getFacultyAbbr().getAbbreviation().equals("FOET") && stud.get(i).getCourseName().getCourseName().toUpperCase().contains(searchStr)){  
            //if(stud.get(i).getFacultyAbbr().getAbbreviation().equals("FOAS") && stud.get(i).getCourseName().getCourseName().toUpperCase().contains(searchStr)){  

                //Gender (F) == faculty == course(Search)
            //if((stud.get(i).getGender()+"").equals("F") && stud.get(i).getFacultyAbbr().getAbbreviation().equals("FOCS") && stud.get(i).getCourseName().getCourseName().toUpperCase().contains(searchStr)){    
            //if((stud.get(i).getGender()+"").equals("F") && stud.get(i).getFacultyAbbr().getAbbreviation().equals("FAFB") && stud.get(i).getCourseName().getCourseName().toUpperCase().contains(searchStr)){    
            //if((stud.get(i).getGender()+"").equals("F") && stud.get(i).getFacultyAbbr().getAbbreviation().equals("FOET") && stud.get(i).getCourseName().getCourseName().toUpperCase().contains(searchStr)){    
            //if((stud.get(i).getGender()+"").equals("F") && stud.get(i).getFacultyAbbr().getAbbreviation().equals("FOAS") && stud.get(i).getCourseName().getCourseName().toUpperCase().contains(searchStr)){    

                //Gender (M) == faculty == course(Search)
            //if((stud.get(i).getGender()+"").equals("M") && stud.get(i).getFacultyAbbr().getAbbreviation().equals("FOCS") && stud.get(i).getCourseName().getCourseName().toUpperCase().contains(searchStr)){    
            //if((stud.get(i).getGender()+"").equals("M") && stud.get(i).getFacultyAbbr().getAbbreviation().equals("FAFB") && stud.get(i).getCourseName().getCourseName().toUpperCase().contains(searchStr)){    
            //if((stud.get(i).getGender()+"").equals("M") && stud.get(i).getFacultyAbbr().getAbbreviation().equals("FOET") && stud.get(i).getCourseName().getCourseName().toUpperCase().contains(searchStr)){    
            //if((stud.get(i).getGender()+"").equals("M") && stud.get(i).getFacultyAbbr().getAbbreviation().equals("FOAS") && stud.get(i).getCourseName().getCourseName().toUpperCase().contains(searchStr)){        

             //filter id first name and last name
             if(idCondition||fNameCondition||lNameCondition){
                     output +=String.format("%-5s%s",(count+1),stud.get(i));
                     found =true;
                     count++;
             }
        }

        if(!found)
            System.out.println("No record found!");
        else{
            System.out.print(s.headerText());
            System.out.print(output);
            System.out.println("\n\nTotal Record = " + count);

        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelTItle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaSearched;
    private javax.swing.JTextField jTextFieldSearchStr;
    // End of variables declaration//GEN-END:variables
}
