<?xml version="1.0" encoding="utf-8"?><Database Name="ARCLibrary" Class="ARCLibraryDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=|DataDirectory|\ARCLibrary.mdf;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ARCLibraryConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Staff" Member="Staffs">
    <Type Name="Staff">
      <Column Name="StaffId" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Hash" Type="System.String" DbType="Char(44) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ContactNo" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
      <Association Name="Staff_LoginInfo" Member="LoginInfos" ThisKey="Username" OtherKey="Username" Type="LoginInfo" />
      <Association Name="Staff_Loan" Member="Loans" ThisKey="StaffId" OtherKey="StaffId" Type="Loan" />
    </Type>
  </Table>
  <Table Name="dbo.Admin" Member="Admins">
    <Type Name="Admin">
      <Column Name="AdminId" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Hash" Type="System.String" DbType="Char(44) NOT NULL" CanBeNull="false" />
      <Association Name="Admin_LoginInfo" Member="LoginInfos" ThisKey="Username" OtherKey="Username" Type="LoginInfo" />
    </Type>
  </Table>
  <Table Name="dbo.Book" Member="Books">
    <Type Name="Book">
      <Column Name="BookId" Type="System.String" DbType="Char(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Author" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(6,2) NOT NULL" CanBeNull="false" />
      <Column Name="ISBN" Type="System.String" DbType="Char(13) NOT NULL" CanBeNull="false" />
      <Column Name="Publisher" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PublishYear" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RegisterDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Image" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="CategoryId" Type="System.String" DbType="Char(3)" CanBeNull="true" />
      <Association Name="Book_Reservation" Member="Reservations" ThisKey="BookId" OtherKey="BookId" Type="Reservation" />
      <Association Name="Book_Loan" Member="Loans" ThisKey="BookId" OtherKey="BookId" Type="Loan" />
      <Association Name="Category_Book" Member="Category" ThisKey="CategoryId" OtherKey="CategoryId" Type="Category" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Category" Member="Categories">
    <Type Name="Category">
      <Column Name="CategoryId" Type="System.String" DbType="Char(3) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CategoryName" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Remark" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Abbreviation" Type="System.String" DbType="Char(3)" CanBeNull="true" />
      <Column Name="PenaltyRate" Type="System.Decimal" DbType="Decimal(3,2) NOT NULL" CanBeNull="false" />
      <Column Name="ReturnDays" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Category_Book" Member="Books" ThisKey="CategoryId" OtherKey="CategoryId" Type="Book" />
    </Type>
  </Table>
  <Table Name="dbo.Member" Member="Members">
    <Type Name="Member">
      <Column Name="MemberId" Type="System.String" DbType="Char(5) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Hash" Type="System.String" DbType="Char(44)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ContactNo" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="Member_Reservation" Member="Reservations" ThisKey="MemberId" OtherKey="MemberId" Type="Reservation" />
      <Association Name="Member_LoginInfo" Member="LoginInfos" ThisKey="Username" OtherKey="Username" Type="LoginInfo" />
      <Association Name="Member_Loan" Member="Loans" ThisKey="MemberId" OtherKey="MemberId" Type="Loan" />
    </Type>
  </Table>
  <Table Name="dbo.Reservation" Member="Reservations">
    <Type Name="Reservation">
      <Column Name="ReservationId" Type="System.String" DbType="Char(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ReserveDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="ReserveDueDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="MemberId" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="BookId" Type="System.String" DbType="Char(6) NOT NULL" CanBeNull="false" />
      <Association Name="Book_Reservation" Member="Book" ThisKey="BookId" OtherKey="BookId" Type="Book" IsForeignKey="true" />
      <Association Name="Member_Reservation" Member="Member" ThisKey="MemberId" OtherKey="MemberId" Type="Member" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BookCategory" Member="BookCategories">
    <Type Name="BookCategory">
      <Column Name="CategoryId" Type="System.String" DbType="Char(3) NOT NULL" CanBeNull="false" />
      <Column Name="CategoryName" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Image" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="BookId" Type="System.String" DbType="Char(6) NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Publisher" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RegisterDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(6,2) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.[User]" Member="Users">
    <Type Name="User">
      <Column Name="Id" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Hash" Type="System.String" DbType="Char(44)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Role" Type="System.String" DbType="VarChar(11) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.BookLoan" Member="BookLoans">
    <Type Name="BookLoan">
      <Column Name="TotalLoan" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Image" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="BookId" Type="System.String" DbType="Char(6) NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Publisher" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="CategoryName" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(6,2) NOT NULL" CanBeNull="false" />
      <Column Name="max_date" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.BookWithCount" Member="BookWithCounts">
    <Type Name="BookWithCount">
      <Column Name="BookCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Author" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CategoryId" Type="System.String" DbType="Char(3)" CanBeNull="true" />
      <Column Name="Image" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="ISBN" Type="System.String" DbType="Char(13) NOT NULL" CanBeNull="false" />
      <Column Name="RegisterDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="PublishYear" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Publisher" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(6,2) NOT NULL" CanBeNull="false" />
      <Column Name="CategoryName" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.LoginInfo" Member="LoginInfos">
    <Type Name="LoginInfo">
      <Column Name="LoginId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Admin_LoginInfo" Member="Admin" ThisKey="Username" OtherKey="Username" Type="Admin" IsForeignKey="true" DeleteRule="SET NULL" />
      <Association Name="Member_LoginInfo" Member="Member" ThisKey="Username" OtherKey="Username" Type="Member" IsForeignKey="true" DeleteRule="SET NULL" />
      <Association Name="Staff_LoginInfo" Member="Staff" ThisKey="Username" OtherKey="Username" Type="Staff" IsForeignKey="true" DeleteRule="SET NULL" />
    </Type>
  </Table>
  <Table Name="dbo.Loan" Member="Loans">
    <Type Name="Loan">
      <Column Name="LoanId" Type="System.String" DbType="Char(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BorrowDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="ReturnDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="StaffId" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="MemberId" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="BookId" Type="System.String" DbType="Char(6) NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="Loan_Penalty" Member="Penalties" ThisKey="LoanId" OtherKey="LoanId" Type="Penalty" />
      <Association Name="Book_Loan" Member="Book" ThisKey="BookId" OtherKey="BookId" Type="Book" IsForeignKey="true" />
      <Association Name="Member_Loan" Member="Member" ThisKey="MemberId" OtherKey="MemberId" Type="Member" IsForeignKey="true" />
      <Association Name="Staff_Loan" Member="Staff" ThisKey="StaffId" OtherKey="StaffId" Type="Staff" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Penalty" Member="Penalties">
    <Type Name="Penalty">
      <Column Name="PenaltyId" Type="System.String" DbType="Char(6) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(6,2) NOT NULL" CanBeNull="false" />
      <Column Name="PayAmount" Type="System.Decimal" DbType="Decimal(6,2) NOT NULL" CanBeNull="false" />
      <Column Name="PayDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="LoanId" Type="System.String" DbType="Char(6)" CanBeNull="true" />
      <Column Name="StaffId" Type="System.String" DbType="Char(6)" CanBeNull="true" />
      <Association Name="Loan_Penalty" Member="Loan" ThisKey="LoanId" OtherKey="LoanId" Type="Loan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PenaltyLoan" Member="PenaltyLoans">
    <Type Name="PenaltyLoan">
      <Column Name="PenaltyId" Type="System.String" DbType="Char(6) NOT NULL" CanBeNull="false" />
      <Column Name="LoanId" Type="System.String" DbType="Char(6)" CanBeNull="true" />
      <Column Name="PayDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Id" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="sUname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="MemberId" Type="System.String" DbType="Char(5) NOT NULL" CanBeNull="false" />
      <Column Name="mUname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(6,2) NOT NULL" CanBeNull="false" />
      <Column Name="PayAmount" Type="System.Decimal" DbType="Decimal(6,2) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>